apiVersion: v1
appVersion: 20150604.0.1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/cdfoundation/artwork/master/jenkinsx/icon/color/jenkinsx-icon-color.png
name: metabase
version: 20150604.0.1
